### ISSUE TITLE
Issue while using on Kotlin 

### ISSUE THREAD

**Issue by ravi-spasystems** [jhonnyx2012/HorizontalPicker#15]
I m getting following issue after selecting a date 

                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'void devs.mulham.horizontalcalendar.utils.HorizontalCalendarListener.onDateSelected(java.util.Calendar, int)' on a null object reference
                                                                     at devs.mulham.horizontalcalendar.utils.HorizontalSnapHelper.notifyCalendarListener(HorizontalSnapHelper.java:46)
                                                                     at devs.mulham.horizontalcalendar.utils.HorizontalSnapHelper.findSnapView(HorizontalSnapHelper.java:37)
                                                                     at android.support.v7.widget.SnapHelper.snapToTargetExistingView(SnapHelper.java:191)
                                                                     at android.support.v7.widget.SnapHelper$1.onScrollStateChanged(SnapHelper.java:53)
                                                                     at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:4759)
                                                                     at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1434)
                                                                     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4908)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:586)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:555)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

**Comment by jhonnyx2012** [comment]
Hi, it's been a while since I release this library and I haven't been compromised with it, I understand that there are many bugs, I'd love to check them all, but I'm really busy at other projects,  so I have to apologize and recommend you to fork this project or make me a PR, I'l review it ASAP.

Cheers!
